production: false
auth:
  direct_grant_url: "http://keycloak.netsoc.local:8080/auth/realms/freeipa/protocol/openid-connect/token"
  jwt:
    public_key: |
      -----BEGIN PUBLIC KEY-----
      MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC rVrCuTtArbgaZzL1hvh0xtL5mc7o0NqPVnYXkLvgcwiC3BjLGw1tGEGoJaXDuSaRllobm53JBhjx33UNv+5z/UMG4kytBWxheNVKnL6GgqlNabMaFfPLPCF8kAgKnsi79NMo+n6KnSY8YeUmec/p2vjO2NjsSAVcWEQMVhJ31LwIDAQAB
      -----END PUBLIC KEY-----
    signing_algorithm: "RS256"
proxmox:
  blacklisted_nodes:
    - feynman
  cluster:
    ssh:
      server: "proxmox.netsoc.local"
      port: 22
      username: "root"
      password: "password"
    api:
      server: "proxmox.netsoc.local"
      port: 8006
      username: "root@pam"
      password: "password"
      token_name: "NetsocCloud"
      token_value: "-"
  lxc:
    inactivity_shutdown_num_days: 48
    inactivity_deletion_num_days: 120
  vps:
    inactivity_shutdown_num_days: 24
    inactivity_deletion_num_days: 48
  network:
    traefik:
      config_key: "77826907276100902243245529368278"
      service_subdomain_cert_resolver: "letsencrypt-dns"
      user_domain_cert_resolver: "letsencrypt-tls"
    port_forward:
      range: [16384, 17384]
    network: "10.10.10.0/24"
    bridge: vmbr1
    vlan: 0
    gateway: "10.10.10.1"
    range: ["10.10.10.3", "10.10.10.60"]
    vhosts:
      user_domain:
        verification_txt_name: "_netsoc"
        allowed_a_aaaa: [84.39.234.51]
      service_subdomain:
        # base domain
        base_domain: "netsoc.local"
    base_fqdn: "netsoc.cloud"
  dir_pool: "local"
  vps:
    templates:
      netsoc-ubuntu-20.04:
        title: "Ubuntu Server 20.04.1 LTS"
        subtitle: "An easy to use server distro"
        description: |
          Ubuntu is a Linux distribution based on Debian mostly composed of free and open-source software.
          Ubuntu is officially released in three editions: Desktop, Server, and Core for Internet of things devices and robots.
          All the editions can run on the computer alone, or in a virtual machine
        logo_url: "https://wiki.netsoc.co/assets/cloud/template-ubuntu.png"
        disk_file: "ubuntu-20.04-server-cloudimg-amd64.img"
        disk_file_fallback_url: "https://cloud-images.ubuntu.com/releases/focal/release-20200921.1/ubuntu-20.04-server-cloudimg-amd64.img"
        disk_sha256sum: "d18a9d2b890d3c1401e70a281cae44b61816aa669c4936f7a99c168e572ec8cb"
        disk_format: "qcow2"
        wake_on_request: no
        specs:
          cores: 2
          disk_space: 10
          memory: 2048
  lxc:
    templates:
      netsoc-devtools-ubuntu:
        title: "Developer Tools (on Ubuntu)"
        subtitle: "Docker, Git, Vim/Nano, Python, NodeJS, Java, C/C++, Rust, Go, Ruby"
        description: |
          Build to your heart's desires with this fully equipped machine
        logo_url: "https://wiki.netsoc.co/assets/cloud/template-devtools.png"
        disk_file: "netsoc-devtools-ubuntu.tar.gz"
        disk_format: "tar.gz"
        wake_on_request: yes
        specs:
          cores: 2
          disk_space: 15
          memory: 1024
          swap: 1024
      netsoc-ghostcms-ubuntu:
        title: "GhostCMS"
        subtitle: "The world's most popular modern professional publishing platform"
        description: |
          Used by Apple, SkyNews, Buffer, OpenAI, and thousands more.
        logo_url: "https://wiki.netsoc.co/assets/cloud/template-ghostcms.png"
        disk_file: "netsoc-ghostcms-ubuntu.tar.gz"
        disk_format: "tar.gz"
        wake_on_request: no
        specs:
          cores: 1
          disk_space: 10
          memory: 512
          swap: 512
      netsoc-lemp-ubuntu:
        title: "LEMP Stack (on Ubuntu)"
        subtitle: "Linux, (e)nginx, MySQL, PHP"
        description: |
          Build classic PHP applications with this instance type.

          Important:
          * The default PHP web root is `/var/www/html/`.
          * Any files in the web root must be owned by `www-data`.
          * You will need to run `mysql_secure_installation` as `root` to configure MySQL.
        logo_url: "https://wiki.netsoc.co/assets/cloud/template-lemp.png"
        disk_file: "netsoc-lemp-ubuntu.tar.gz"
        disk_format: "tar.gz"
        wake_on_request: no
        specs:
          cores: 1
          disk_space: 10
          memory: 1024
          swap: 1024
      netsoc-linuxgsm-ubuntu:
        title: "LinuxGSM"
        subtitle: "Quick, simple deployment and management of dedicated game servers."
        description: |
          An instance built for LinuxGSM. Create servers like:
          * CS:GO
          * Garry's Mod
          * Minecraft
          * Many other games: <a href="https://linuxgsm.com/servers/" target="_blank">https://linuxgsm.com/servers/</a>


          Follow the installation steps on LinuxGSM's website to install the gameserver you require
        logo_url: "https://wiki.netsoc.co/assets/cloud/template-linuxgsm.png"
        disk_file: "netsoc-linuxgsm-ubuntu.tar.gz"
        disk_format: "tar.gz"
        wake_on_request: no
        specs:
          cores: 2
          disk_space: 25
          memory: 2048
          swap: 2048
      netsoc-mean-ubuntu:
        title: "MEAN Stack (on Ubuntu)"
        subtitle: "MongoDB, express, Angular, NodeJS"
        description: |
          Everything you need to get started creating the modern website of your dreams
        logo_url: "https://wiki.netsoc.co/assets/cloud/template-mean.png"
        disk_file: "netsoc-mean-ubuntu.tar.gz"
        disk_format: "tar.gz"
        wake_on_request: no
        specs:
          cores: 1
          disk_space: 10
          memory: 1024
          swap: 1024
      netsoc-mysql-ubuntu:
        title: "MySQL"
        subtitle: "The relational database everyone knows and uses"
        description: |
          A simple MySQL server configured for remote access.

          Visit the instance page on creation to configure the admin user
        logo_url: "https://wiki.netsoc.co/assets/cloud/template-mysql.png"
        disk_file: "netsoc-mysql-ubuntu.tar.gz"
        disk_format: "tar.gz"
        wake_on_request: no
        specs:
          cores: 1
          disk_space: 10
          memory: 1024
          swap: 1024
      netsoc-wordpress-ubuntu:
        title: "WordPress"
        subtitle: "The most popular blog and CMS system"
        description: |
          WordPress is a free and open-source content management system (CMS) written in PHP and paired with a MySQL or MariaDB database.
        logo_url: "https://wiki.netsoc.co/assets/cloud/template-wordpress.png"
        disk_file: "netsoc-wordpress-ubuntu.tar.gz"
        disk_format: "tar.gz"
        wake_on_request: yes
        specs:
          cores: 1
          disk_space: 10
          memory: 512
          swap: 512
      netsoc-ubuntu-20.04:
        title: "Ubuntu Server 20.04.1 LTS"
        subtitle: "Ubuntu Server 20.04.1 LTS"
        description: |
          Ubuntu is a Linux distribution based on Debian mostly composed of free and open-source software.
          Ubuntu is officially released in three editions: Desktop, Server, and Core for Internet of things devices and robots.
          All the editions can run on the computer alone, or in a virtual machine
        logo_url: "https://wiki.netsoc.co/assets/cloud/template-ubuntu.png"
        disk_file: "ubuntu-20.04-standard_20.04-1_amd64.tar.gz"
        disk_file_fallback_url: "http://download.proxmox.com/images/system/ubuntu-20.04-standard_20.04-1_amd64.tar.gz"
        disk_sha256sum: "23895b40c84d04a666616ea2f7b9441df62133790bb51d83ee7e2c076ff89c89"
        disk_format: "tar.gz"
        wake_on_request: no
        specs:
          cores: 1
          disk_space: 10
          memory: 1024
          swap: 1024

links:
  base_url: "http://cloud.netsoc.local"
  jwt:
    public_key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5Co+UQw9fJj4k+1cZCFu
      1bLcspl87qMSieM7qg+BPckfwrP0WrSgu8i4pUzmiP+sZrXQ2/WC6UF6bUc3CHfz
      yEJj20iUj8heSvvjqoMMMASrJSCXabOPE2Bp6XGIwx+S086EiK8HrpnUkrQSHn4M
      whiGjeXzoi/LMLBO/Jl6OB7F51TGIG62NLW9dPfEwgAvm09vHz/cy2p/denmLO7Z
      kyQcmkPAUpsuBvaoQmkNl2IW2l/2YEMxN++XWxuWsrFXgKOYkG8Ira5c4y6930Rq
      +ehtU3p1rXAueAJ6fmTW0TZ7/KCjYvUOLSslx0T3cYlzaj7v5G9nbqoy/oXl3Qqb
      VQIDAQAB
      -----END PUBLIC KEY-----
    private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpAIBAAKCAQEA5Co+UQw9fJj4k+1cZCFu1bLcspl87qMSieM7qg+BPckfwrP0
      WrSgu8i4pUzmiP+sZrXQ2/WC6UF6bUc3CHfzyEJj20iUj8heSvvjqoMMMASrJSCX
      abOPE2Bp6XGIwx+S086EiK8HrpnUkrQSHn4MwhiGjeXzoi/LMLBO/Jl6OB7F51TG
      IG62NLW9dPfEwgAvm09vHz/cy2p/denmLO7ZkyQcmkPAUpsuBvaoQmkNl2IW2l/2
      YEMxN++XWxuWsrFXgKOYkG8Ira5c4y6930Rq+ehtU3p1rXAueAJ6fmTW0TZ7/KCj
      YvUOLSslx0T3cYlzaj7v5G9nbqoy/oXl3QqbVQIDAQABAoIBABkbvPfWTP3lJ5W/
      zScHtta1dCwDUAhC0ctywiIYyrQt6dzXSNCih/2iPQ+TwtrYp/Q1leJexiU9G2fj
      Kl84NA+ZnruG5TJdbmL6DTe6bCDsopjXWVI8fEY5me4inFY8pz+/vj38ZPAF5aqv
      Pj80x9qkMEp1P7ZdZBLblBWgHh8GrqmxJsEv4ipvH22wLv4D+y784pxRzqsv18h1
      6opEw6XYPdv/zZ4aSlXRERH+U0DGHdwC/FCX5m6nlK+RCyMY9jY2VgsDSTbHpEq8
      ABoCpz9J/1yw9OYVOvc2MPiW0ONxAadKMAhKBOU9+sRxWYOy/OublBBxjMmBlpXU
      3xC3U5ECgYEA/MFDvTX7JiPJLHVPyT5kczwKR3+hgF6RxaDcozSE27k7YXCEkNKD
      QMAhMuY+jIkiej2ej84gyDkIRkpGlZKWRXvlrcwhBVQGWgJbV6ztZ0C35aQHP30i
      06l0SDaarkfLJ40diTyV8ZS+ZL1vxhRxR3Oi2p82yUxBWNyNGYBnZAsCgYEA5xgo
      lq0peCFZQuC3k6UC6rIv8TNEzdYcWPy/WNRf17Ta07fQu/+Zi02HQ45zTGk2bmQ3
      GFoK4AfrUM/iHPMXwhwmaM1YOl4HCFTRT4yv2lYucrfQ3Z+vbfWPd8Ex5bkzfZnU
      V4quuTtSfIPvrLY+WAdYps4JuAJg5cvOUBFxOh8CgYAc3AhbA13g1fczb1Wj2c7o
      ZXObBFSxbprgYOSwcd+1ounHz2wjiRXZf9aKlEWSEFpycLS5IMUXd4OdWv/CNlGY
      L3RjKsqebCCpiFlbonAc+QPGYbs+IZCncFLJqApzWdk1c+RqdhN82QoAQK0RheYF
      TYvLwKAlzeIsPkqSHdowTwKBgQCa32zsNhaRpL/eex1sfGzs/wf0POjCjdinppNS
      I9orhNAWjZz9MTokyot5MfGBZw2Mg+sMjeO16njAyuD9h8kHVLhFCkEztKo/4h/4
      kQ+VYqZ0SU5YCNmX9rb0iew3yZuBdGODW7Tm/KO2QPGSLPyxIBNAjtqikC2CM8kL
      jfT0/wKBgQDGI+txHkl+NSZc889sGL7h+mNg1i7BXXLfmG/2HahYF6QiO1cnIC0a
      gohQO9sbxUCk3Vj/f+zqsa9pbC2mZkgvaOr9unhuxNKnkUIOHyCqQi1u0YA9t8e5
      /+RtZ8ZrqQNLY8Yta/mXSuycnLCkF0+/7Rx4DIRK/0Oo4gbRwduTAg==
      -----END RSA PRIVATE KEY-----
accounts:
  home_dirs: "/home/users"
  freeipa:
    server: "ipa.netsoc.local"
    username: "admin"
    password: "netsoc_freeipa"
webhooks:
  info: https://discordapp.com/api/webhooks/732754216883585059/6LqFp1ZsomNdlMT78PBJCQNXN5hq_luwiec4UxTVcRpLErSnLWCi7SRnMKztIYRoSK-t
  form_filled: https://discordapp.com/api/webhooks/732754216883585059/6LqFp1ZsomNdlMT78PBJCQNXN5hq_luwiec4UxTVcRpLErSnLWCi7SRnMKztIYRoSK-t
email:
  sendgrid:
    key: "- no pls -"
captcha:
  enabled: true
  hcaptcha:
    secret: "0xA31cDbEC6b6d1bBB8c83566AdCC84B98F09b6d1c"
