version: "3.7"
services:
  traefik.netsoc.local:
    image: traefik:2.2.0
    ports:
      - "80:80"
      - "443:443"
    labels:
      # global redirect to https
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.netsoc.local`)"
      - "traefik.http.routers.dashboard.service=dashboard-service"
      - "traefik.http.services.dashboard-service.loadbalancer.server.port=8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./traefik:/traefik/"
    command: traefik --configFile=/traefik/static_config.yml
  user_websites.netsoc.local:
    image: nginx
    volumes:
      - "./user_websites/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./user_websites/home:/home"
  nsa3.netsoc.local:
    build:
      context: "./ui"
    command: npm run serve
    volumes:
      - "./ui/:/app"    
  account.nsa3.netsoc.local:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.7
    ports:
      - 0.0.0.0:8083:8080
    volumes:
      - "./account/v1:/app/v1/"
      - "./account/requirements.txt:/requirements.txt"
      - "./account/prestart.sh:/app/prestart.sh"
    command: /start-reload.sh --host 0.0.0.0 --debug --port 8080
    environment:
      MODULE_NAME: "v1.main"
      VARIABLE_NAME: "api"
  ipa.netsoc.local:
    image: freeipa/freeipa-server:latest
    command: >
      ipa-server-install
      --unattended
      --realm=netsoc.local
      --ds-password=netsoc_freeipa
      --admin-password=netsoc_freeipa
      --no-host-dns
    hostname: ipa.netsoc.local
    read_only: true
    environment:
      IPA_SERVER_HOSTNAME: ipa.netsoc.local
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "/etc/machine-id:/etc/machine-id:ro"
      - "./freeipa/data:/data:z"
    sysctls:
      net.ipv6.conf.lo.disable_ipv6: 0
      # Fixes:
      # DEBUG The ipa-server-install command failed, exception: 
      # RuntimeError: IPv6 stack is enabled in the kernel but there is no interface that has ::1 address assigned.
      # Add ::1 address resolution to "lo" interface. You might need to enable IPv6 on the interface "lo" in sysctl.conf.
    # ports:
    #   - 80:80
    #   - 443:443
    #   - "389:389"   # ldap
    #   - "636:636"   # ldaps
    #   - "88:88"     # kerberos
    #   - "464:464"   # kpasswd 
    #   - "749:749"   # kpasswd
    #   - "123:123"   # ntp
  keycloak.netsoc.local:
    image: jboss/keycloak:9.0.3
    environment:
      KEYCLOAK_USER: netsoc_keycloak
      KEYCLOAK_PASSWORD: netsoc_keycloak
      DB_VENDOR: postgres
      DB_ADDR: postgres.netsoc.test
      DB_DATABASE: netsoc_keycloak
      DB_USER: netsoc_keycloak
      DB_PASSWORD: netsoc_keycloak
      KEYCLOAK_IMPORT: /tmp/keycloak/freeipa-realm.json
    depends_on:
      - "ipa.netsoc.local"
    hostname:
      keycloak.netsoc.local
    volumes:
      - "./keycloak/:/tmp/keycloak/"
      - "./keycloak/krb5.keytab:/krb5.keytab"
  postgres.netsoc.test:
    image: postgres
    environment:
      POSTGRES_USER: netsoc_keycloak
      POSTGRES_PASSWORD: netsoc_keycloak
      POSTGRES_DB: netsoc_keycloak
  proxy.netsoc.local:
    image: wernight/dante
    ports:
      - "0.0.0.0:1080:1080"
  whoami.netsoc.local:
    image: containous/whoami
