version: "3.7"
services:
  #nsa3.netsoc.local:
  account.nsa3.netsoc.local:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.7
    ports:
      - 8083:8080
    volumes:
      - "./account/v1:/app/v1/"
      - "./account/requirements.txt:/requirements.txt"
      - "./account/prestart.sh:/app/prestart.sh"
    command: /start-reload.sh --host 0.0.0.0 --port 8080
    environment:
      MODULE_NAME: "v1.main"
      VARIABLE_NAME: "api"
  keycloak.netsoc.local:
    image: keycloak-freeipa-client:latest
    privileged: true
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: netsoc_keycloak
      KEYCLOAK_PASSWORD: netsoc_keycloak
      DB_VENDOR: postgres
      DB_ADDR: postgres.netsoc.test
      DB_DATABASE: netsoc_keycloak
      DB_USER: netsoc_keycloak
      DB_PASSWORD: netsoc_keycloak
      KEYCLOAK_IMPORT: /tmp/keycloak/freeipa-realm.json
      PASSWORD: netsoc_freeipa
      IPA_PORT_80_TCP_ADDR: "ipa.netsoc.local"
      IPA_CLIENT_INSTALL_OPTS: "--server=ipa.netsoc.local --domain=netsoc.local"
      IPA_REALM: NETSOC.LOCAL
    depends_on:
      - "ipa.netsoc.local"
    hostname:
      keycloak.netsoc.local
    volumes:
      - "./account/dev-env/keycloak/:/tmp/keycloak/"
  postgres.netsoc.test:
    image: postgres
    environment:
      POSTGRES_USER: netsoc_keycloak
      POSTGRES_PASSWORD: netsoc_keycloak
      POSTGRES_DB: netsoc_keycloak
  ipa.netsoc.local:
    image: freeipa/freeipa-server:latest
    command: >
      --unattended
      --realm=netsoc.local
      --ds-password=netsoc_freeipa
      --admin-password=netsoc_freeipa
      --no-host-dns
    hostname: ipa.netsoc.local
    read_only: true
    environment:
      IPA_SERVER_HOSTNAME: ipa.netsoc.local
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "/etc/machine-id:/etc/machine-id"
      - "./account/dev-env/freeipa:/data:z"
    sysctls:
      net.ipv6.conf.lo.disable_ipv6: 0
      # Fixes:
      # DEBUG The ipa-server-install command failed, exception: 
      # RuntimeError: IPv6 stack is enabled in the kernel but there is no interface that has ::1 address assigned.
      # Add ::1 address resolution to "lo" interface. You might need to enable IPv6 on the interface "lo" in sysctl.conf.
    ports:
      - 80:80
      - 443:443
      - "389:389"   # ldap
      - "636:636"   # ldaps
      - "88:88"     # kerberos
      - "464:464"   # kpasswd 
      - "749:749"   # kpasswd
      - "123:123"   # ntp
  proxy.netsoc.local:
    image: wernight/dante
    ports:
      - "1080:1080"
  whoami.netsoc.local:
    image: containous/whoami
  nsa3.netsoc.local:
    build:
      context: "./ui"
    command: npm run serve
    volumes:
      - "./ui/:/app"    